version: '3.7'

services:
  bun-test-hot-reload:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    container_name: bun-test-hot-reload
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: bun run dev